//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stoneFenceProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildEvents
    {
        public int id { get; set; }
        public Nullable<int> child_id { get; set; }
        public Nullable<int> event_id { get; set; }
        public bool attendance { get; set; }
        public string notes { get; set; }
    
        public virtual Events Events { get; set; }
    }
}
