//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stoneFenceProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationInfo
    {
        public int id { get; set; }
        public Nullable<int> child_id { get; set; }
        public string school { get; set; }
        public string education_program { get; set; }
    }
}
