//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stoneFenceProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public int id { get; set; }
        public Nullable<int> child_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string note_text { get; set; }
        public System.DateTime date_created { get; set; }
    }
}
