//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stoneFenceProj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OVZDatabaseEntities : DbContext
    {
        public OVZDatabaseEntities()
            : base("name=OVZDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChildEvents> ChildEvents { get; set; }
        public virtual DbSet<Children> Children { get; set; }
        public virtual DbSet<EducationInfo> EducationInfo { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<HealthInfo> HealthInfo { get; set; }
        public virtual DbSet<Notes> Notes { get; set; }
        public virtual DbSet<Resources> Resources { get; set; }
        public virtual DbSet<Specialists> Specialists { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
